name: Test Node.js

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    environment: node-test

    env:
      SPEECHIFY_API_KEY: ${{ secrets.SPEECHIFY_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: cd nodejs && corepack enable && pnpm install

      - run: cd nodejs && pnpm exec playwright install chromium && pnpm build && pnpm test:browser
